### ISSUE TITLE
Admin page without being logged in

### ISSUE THREAD

**Issue by GreenBeard** [Pigmice2733/scouting-frontend#47]
If one is not logged in and they visit https://scouting.netlify.com/admin it will redirect to [/login](https://scouting.netlify.com/login), but it will not ever show the login screen.

**Comment by calebeby** [comment]
Hm interesting error, will look into this

**Comment by GreenBeard** [comment]
It seems to somehow be fixed?

**Comment by calebeby** [comment]
Yeah, I guess? I'm going to close, if we see it again we can repoen
